version: '3.7'

services:
    # PostgresSQL
    db:
        container_name: postgres
        image: postgres:15.2
        restart: always
        ports:
            - "5433:5432"
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks:
            - service

    # Redis
    redis:
        container_name: redis
        image: redis:alpine
        ports:
            - "6379:6379"
        networks:
            - service

    # Laravel Echo Server (WebSocket)
    echo-server:
        container_name: laravel-echo-server
        build:
            context: ./
            dockerfile: Dockerfile-echo-server
        volumes:
            - ./:/app
        ports:
            - "6001:6001"
        depends_on:
            - redis
        networks:
            - service

volumes:
    postgres-data:

networks:
    service:
