version: '3.7'

services:
    # PostgresSQL
    db:
        container_name: postgres
        image: postgres:15.2
        restart: always
        ports:
            - "5433:5432"
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks:
            - service

volumes:
    postgres-data:

networks:
    service:
